Progetto_PineappleMusic/Codice/music/routes.py
from flask import Blueprint, render_template, flash,redirect,url_for, request, abort
from flask_login import  login_required,current_user

import json
from Codice.user.forms import TableChoice

from Codice.models import *
from Codice.database import *
from .forms import DeletePlaylist, DeleteSongFromPlaylist, PlaylistForm,AddToPlaylist,GetSongsPlaylist,GetSongsGenres


# Blueprint Configuration
music = Blueprint('music', __name__, static_folder='static',
                 template_folder='templates')


@music.route('/views', methods=['GET','POST'])
@login_required
def views():
    var=request.data
    data = json.loads(var)
    #print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAa", var)
    #if data["upvote"] == "up":
    #    print("AAAAAAAAAAAAAAAAAAAAAAAA")
    
    if data["view"] == "true":
        Statistic.increase_views(int(data["idsong"]),current_user.type_session)
        #print("AAAAAAAAAAAAAAAAAAAAAAAAAA")  
    elif "upvote" in data:
        if data["upvote"] == "up":
            like = True
            Record.delete(current_user.username, int(data["idsong"]),current_user.type_session)
            Record.insert(current_user.username, int(data["idsong"]), like,current_user.type_session)  
        elif data["downvote"] == "down":
            like = False
            Record.delete(current_user.username, int(data["idsong"]), current_user.type_session)
            Record.insert(current_user.username, int(data["idsong"]), like, current_user.type_session)  
        elif data["upvote"] == "null" and data["downvote"] == "null":
            Record.delete(current_user.username, int(data["idsong"]), current_user.type_session)
        
    return "ok"



@music.route('/search', methods=['GET','POST'])
@login_required
def search():
    form=AddToPlaylist()
    
    print(current_user.type_session,current_user.username)

    playlist = Playlist.get_playlist_user(current_user.type_session,current_user.username)
    form.playlist.choices=Playlist.get_playlist_name_id(current_user.type_session,playlist)

    song=Song.get_songs(current_user.username,current_user.type_session)

    
    
    
    if form.validate_on_submit():
        for idl in form.playlist.data:
            Contains.create(form.songid.data, idl, current_user.type_session)
    
    return render_template("songs.html",user=current_user,page_name="Search Songs",add_to_playlist=True,
                           listsong=song,playlist=playlist,form=form)


@music.route('/playlist', methods=['GET','POST'])
@login_required
def playlist():
    form=PlaylistForm()
    playlistform=GetSongsPlaylist()
    deleteplaylist=DeletePlaylist()
    session=current_user.type_session
    if form.validate_on_submit():
        if Playlist.create(session,form.name.data,current_user.username):
            flash("Succesful Creation")
        else:
            flash("Creation Failed")
    
    if deleteplaylist.validate_on_submit():
        Playlist.delete_playlist(deleteplaylist.playlistid.data, current_user.type_session)
            
    return render_template("playlist.html",user=current_user, form=form,
                           playlistform=playlistform,delete_playlist=deleteplaylist,
                           playlist=Playlist.get_playlist_user(session,current_user.username))


@music.route('/getsongfromplaylist', methods=['POST'])
@login_required
def getsongfromplaylist():
    form=GetSongsPlaylist()
    delete_form=DeleteSongFromPlaylist()
    if form.validate_on_submit():
        if delete_form.validate_on_submit():
            Contains.delete_song_from_playlist(delete_form.idsong.data,delete_form.playlistid.data, current_user.type_session)

        song=Song.get_song_playlist(current_user.username,form.playlistid.data)
        return render_template("songs.html",user=current_user,page_name="Playlist",
                listsong=song,delete_from_playlist=True,delete_form=delete_form,playlistid=form.playlistid.data)


@music.route('/getsongfromplaylist', methods=['GET'])
@login_required
def getsongfromplaylist_redirect():
    return redirect(url_for('music.playlist'))


@music.route('/getsongfromgenre', methods=['POST'])
@login_required
def getsongfromgenre():
    form=AddToPlaylist()
    genre_form=GetSongsGenres()
    session=User.get_type_user_session(current_user.username)

    if genre_form.validate_on_submit():
        song = Song.get_songs(current_user.username,current_user.type_session, genre_form.genre.data)

        playlist = Playlist.get_playlist_user(session,current_user.username)
        form.playlist.choices=Playlist.get_playlist_name_id(session,playlist)
        
        if form.validate_on_submit():
            for idl in form.playlist.data:
                Contains.create(form.songid.data, idl, current_user.type_session)
        
        return render_template("songs.html",user=current_user,page_name=genre_form.genre.data,add_to_playlist=True,
                            listsong=song,playlist=playlist,form=form)


@music.route('/getsongfromgenre', methods=['GET'])
@login_required
def getsongfromgenre_redirect():
    return redirect(url_for('user.home'))



@music.route('/getsongfromhome', methods=['GET'])
@login_required
def getsongfromhomeget_redirect():
    return redirect(url_for('user.home'))


@music.route('/getsongfromhome', methods=['POST'])
@login_required
def getsongfromhome():
    form_choice = TableChoice()
    form=AddToPlaylist()
    if form_choice.validate_on_submit():
        
        if form_choice.choice.data == 'views':
            song = Song.get_top_view_songs(current_user.type_session,True,current_user.username)
            pagename="TOP 10 VIEWS"
        elif form_choice.choice.data == 'likes':
            song = Song.get_top_like_songs(current_user.type_session,True,current_user.username)
            pagename="TOP 10 LIKES"
        elif form_choice.choice.data == 'suggestions':
            song = Song.get_suggestion_songs(current_user.username,current_user.type_session, True)
            pagename="YOUR SUGGESTION"
            if song == None:
                song = Song.get_top_view_songs(current_user.type_session,True,current_user.username)
        else:
            abort(412)
        playlist = Playlist.get_playlist_user(current_user.type_session,current_user.username)
        form.playlist.choices=Playlist.get_playlist_name_id(current_user.type_session,playlist)
        
    return render_template("songs.html",user=current_user,page_name=pagename,add_to_playlist=True,
                            listsong=song,playlist=playlist,form=form)

Progetto_PineappleMusic/Codice/user/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, logout_user, current_user

from Codice.database import *
from Codice.user.forms import CrediCardForm, ModifyProfileForm, TableChoice
from Codice.music.forms import GetSongsGenres
from Codice.models import *

# Blueprint Configuration
user = Blueprint('user', __name__, static_folder='static',
                 template_folder='templates')


@user.route('/home', methods=['GET'])
@login_required
def home():
    likes = Song.get_top_like_songs(current_user.type_session)
    views = Song.get_top_view_songs(current_user.type_session)
    suggestion = Song.get_suggestion_songs(current_user.username, current_user.type_session)
    print("SUGGESTION: ", suggestion)
    if suggestion == None:
        suggestion = views
    form_redirect = TableChoice()    
    form_genre=GetSongsGenres()
    genres=Genre.get_genres()
    
    return render_template("home.html", title="Home", form_genre=form_genre,user=current_user,genres=genres, songview = views, songlike = likes, songsuggestion = suggestion, form_redirect = form_redirect)


@user.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = ModifyProfileForm()
    if form.validate_on_submit():
        if form.password.data == '':
            check_password = False
        else:
            check_password = True
            form.password.data = User.encrypt_password(form.password.data)
        if User.update_user(current_user.type_session,
                            current_user.username, form.name.data,
                            form.surname.data, form.birthdate.data,
                            form.password.data, form.phone.data, form.email.data,
                            check_password):
            flash('Update Successful')
            return redirect(url_for('user.profile'))
        else:
            flash('Update Failed')
    return render_template("profile.html", title="Profile", user=current_user, form=form)


@user.route('/delete', methods=['POST'])
@login_required
def delete():
    User.delete_user(current_user.username)
    logout_user()
    flash('Your account was deleted.')
    return redirect(url_for('auth.signin'))


@user.route('/premium', methods=['GET', 'POST'])
@login_required
def premium():
    form = CrediCardForm()
    if form.validate_on_submit():
        if not form.card_number.data.isnumeric():
            flash("Card Number not valid.(Don't use letters!)")
        elif not form.cvv.data.isnumeric():
            flash("CVV not valid(Don't use letters!)")
        else:
            if User.move_user_to_premium(current_user.username):
                flash("Ugrade Succesful. YOU ROCK!")
            else:
                flash("Upgrade Failed.")
    return render_template("premium.html", title="Premium Account", user=current_user, form=form)

Progetto_PineappleMusic/Codice/templates/base.html
<!DOCTYPE html>
<html>
<head>

    <title>{{title}} - PinappleMusic</title>

    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/pineapplemusic.ico')}}">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/datatable-bootstrap.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-select.css')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/style.css') }}">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js"></script>

    {% block css %}{% endblock %}
    
</head>

<body>
    {% block pagebody %}{% endblock %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.6.0.min.js')}}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/popper.js')}}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-select.js')}}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-datatable.js')}}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/datatable-bootstrap.js')}}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/datatable-select.js')}}"></script>
    

    

    <script type="text/javascript" src="{{ url_for('static', filename='js/script.js')}}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/fontawesome.js')}}"></script>
    <!--import icons-->
    {% block js %}{% endblock %}
</body>
</html>

Progetto_PineappleMusic/Codice/templates/menu.html
{% extends "base.html" %}
{% block pagebody %}



<div class="main-container d-flex">
    <!--black sidebar-->
    <div class="sidebar" id="side_nav">
        <div class="head-box px-2 pt-3 pb-4 d-flex justify-content-between">
            <h1 class="fs-4">
                <img class="mb-4" src="{{ url_for('static',filename='img/pineapplemusic.ico') }}" alt="logo" width="36"
                    height="50">
                <span class="text-white">PineappleMusic</span>
            </h1>
            <button class="btn d-mb-none d-block close-btn px-1 py-0 text-white d-md-none d-block">
                <i class="fa-solid fa-bars-staggered"></i>
            </button>
        </div>
        <ul class="list-unstyled px-2">
            <li><a href="{{url_for('user.home')}}" class="text-decoration-none px-3 py-2 d-block"><i
                        class="fa-solid fa-house"></i>Home</a></li>
            <li><a href="{{url_for('music.search')}}" class="text-decoration-none px-3 py-2 d-block"><i
                        class="fa-solid fa-magnifying-glass"></i>Search</a></li>


            <li><a href="{{url_for('music.playlist')}}" class="text-decoration-none px-3 py-2 d-block"><i
                        class="fa-solid fa-list-ol"></i>Playlist</a></li>
            <li><a href="{{url_for('user.profile')}}" class="text-decoration-none px-3 py-2 d-block"><i
                        class="fa-solid fa-user"></i>Profile</a></li>
            
            {% if user.type_account == 1%}
                <li><a href="{{url_for('user.premium')}}" class="text-decoration-none px-3 py-2 d-block">
                    <i class="fa-solid fa-star"></i>Premium</a></li>
            {% endif%}

            {% if user.type_account == 3%}
                <li><a href="{{url_for('artist.album')}}" class="text-decoration-none px-3 py-2 d-block">
                    <i class="fa-solid fa-compact-disc"></i>Album</a></li>
                
                <li><a href="{{url_for('artist.song')}}" class="text-decoration-none px-3 py-2 d-block">
                    <i class="fa-solid fa-music"></i>Song</a></li>
                
                <li><a href="{{url_for('artist.statistics')}}" class="text-decoration-none px-3 py-2 d-block">
                    <i class="fa-solid fa-gauge-high"></i>Statistics</a></li>
            {% endif%}
        </ul>
        <!--bottom part of sidebar that contains name to exit from account-->
        <hr class="h-color mx-2">
        <div class=" d-block " id="exitaccount">
            <ul class="list-unstyled px-2">
                <li>
                    <a href="{{url_for('auth.signout')}}" class="text-decoration-none px-3 py-2 ">
                        <i class="fa-solid fa-right-from-bracket"></i>
                        {{user.username}}
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <!--top bar seen by phone/small screen-->
    <div class="content " style="background-color: #FFFFFF"  >
        <nav class="navbar navbar-expand-md navbar-light d-md-none d-block" style="background-color: #000">
            <div class="container-fluid">
                <div class="d-flex justify-content-between d-md-none d-block">
                    <a class="navbar-brand fs-4 text-white" href="#">Pineapple Music</a>
                    <button class="btn px-1 py-0 open-btn text-white"><i class="fa-solid fa-bars-staggered"></i></button>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                </div>
            </div>
        </nav>
   
    {% block content %}
    {% endblock %}
    </div>
</div>

{% endblock %}