Progetto_PineappleMusic/Codice/artist/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, abort
from flask_login import login_required, current_user

from Codice.models import *
from Codice.database import *
from Codice.artist.forms import *

# Blueprint Configuration
artist = Blueprint('artist', __name__, static_folder='static',
                 template_folder='templates')


@artist.route('/statistics', methods=['GET'])
@login_required
def statistics():
    if current_user.type_account != 3:
        abort(403)
    views=Statistic.get_statistics(current_user.username,current_user.type_session)
    return render_template('statistics.html', user = current_user,views=views)



@artist.route('/song', methods=['GET','POST'])
@login_required
def song():
    if current_user.type_account != 3:
        abort(403)
            
    form = SongForm()
    modify_song=ModifySong()
    delete_song=DeleteSong()
    form.genre.choices = Genre.get_genre_list_database()
    
    #albums managment
    list_albums = Album.get_albums_username(current_user.username)
    list_albums_names = Album.get_albums_name(temp_username= current_user.username,albums= list_albums, choice = None)
    form.album.choices = list_albums_names
    songs= Song.get_songs_artist(current_user.username)
    
    if form.validate_on_submit():
        if Artist.check_link(form.content.data):
            if (form.cover.data == None) and (form.album.data == ''):
                flash("Insert a cover.")
            else:
                if form.genre.data == '':
                    flash("Select a genre")
                else:
                    if form.premium.data == '':
                        flash("Select Exclusivity")
                    else:
                        if form.album.data == '':#no album
                            if Artist.check_link(form.cover.data):    
                                if Artist.insert_song(form.name.data, None, form.cover.data.split("/")[5], form.release_date.data,
                                                form.content.data.split("/")[5],current_user.username,form.genre.data,form.premium.data,current_user.type_session):
                                    flash("Upload Succesfull")
                                    redirect(url_for('artist.song'))
                                else:
                                    flash("Upload Failed")
                            else:
                                flash("Cover not Inserted")
                        else:#album
                            album = Album.extract_id_album(list_albums,form.album.data)
                            cover = Album.extract_cover_album(list_albums, form.album.data)
                            if album == None or cover == None:
                                flash("Error Register Ablum")
                            else:
                                if Artist.insert_song(form.name.data, album, cover, form.release_date.data,
                                            form.content.data.split("/")[5],current_user.username,form.genre.data,form.premium.data,current_user.type_session):
                                    flash("Upload Successful")
                                    redirect(url_for('artist.song'))
                                else:
                                    flash("Upload Failed")
        else:
            flash("Cover or content links are invalid")
    return render_template('song.html', form = form, user = current_user,songs=songs,modify_song=modify_song,delete_song=delete_song)


@artist.route('/album', methods=['GET','POST'])
@login_required
def album():
    if current_user.type_account != 3:
        abort(403)
        
    form = AlbumForm()
    delete_album=DeleteAlbum()
    modify_album=ModifyAlbum()
    
    print(current_user)
    
    if form.validate_on_submit():
        if Album.check_artist_album_name(form.name.data, current_user.username):
            flash("Album name already in use by you.")
        else:
            if Artist.check_link(form.cover.data):
                if Artist.insert_album(form.name.data,form.cover.data.split("/")[5],current_user.username):
                    flash("Upload Successful.")
                else:
                    flash("Upload Failed.")
            else:
                flash("Invalid cover link.")
                
    return render_template('album.html', form = form, user = current_user,
                           delete_album=delete_album,
                           modify_album=modify_album,
                           album=Album.get_albums_username(current_user.username))



@artist.route('/modifyalbum', methods=['GET'])
@login_required
def modifyalbum_redirect():
    if current_user.type_account != 3:
        abort(403)
    return redirect(url_for('artist.album'))

@artist.route('/modifyalbum', methods=['POST'])
@login_required
def modifyalbum():
    if current_user.type_account != 3:
        abort(403)
        
    modify_album=ModifyAlbum()
    album_form =ModifyAlbumForm()
    if album_form.validate_on_submit():
        if album_form.name.data == Album.get_albums_id(album_form.idalbum.data).name and album_form.cover.data == '':
            flash("No nodification made")
            return redirect(url_for('artist.album'))
        else:
            if Artist.modify_album(album_form.idalbum.data,album_form.name.data,album_form.cover.data,current_user.username, current_user.type_session):
                flash("Successful modification.")
                return redirect(url_for('artist.album'))
            else:
                flash("Error Modification")  
    return render_template('modifyalbum.html', form = album_form, album = Album.get_albums_id(modify_album.idalbum.data), user = current_user)

@artist.route('/deletealbum', methods=['POST'])
@login_required
def deletealbum():
    if current_user.type_account != 3:
        abort(403)
        
    delete_album=DeleteAlbum()
    if delete_album.validate_on_submit():
        if Artist.delete_album(delete_album.idalbum.data, current_user.type_session):
            flash("Album Deleted.")
        else:
            flash("Error Deleting Album.")
        #delete
    return redirect(url_for('artist.album'))

@artist.route('/modifysong', methods=['GET','POST'])
@login_required
def modifysong():
    if current_user.type_account != 3:
        abort(403)
        
    song = ModifySong()
    form = ModifySongForm()
    song_info = Song.get_song_id(song.idsong.data)
    
    #genre choice
    form.genre.choices = Belong.get_genre_list(song.idsong.data, current_user.type_session)
    
    #album managment
    list_albums = Album.get_albums_username(current_user.username)
    list_albums_names = Album.get_albums_name(current_user.username,list_albums,song_info.album)
    form.album.choices = list_albums_names
    
    if form.validate_on_submit():
        #modify song con campy giusti
        #verificare se codificato singolarmente
        album = 2
        if form.name.data == song_info.name:#name
            form.name.data = None        
        
        if form.genre.data == form.genre.choices[0]:#genre 
            form.genre.data = None
            
        if form.premium.data == '':#premium
            form.premium.data = None
        elif form.premium.data == 'The song will be premium':
            if not PremiumSong.check_song(form.name.data, current_user.type_session):
                form.premium.data = 1
            else:
                form.premium.data = None
        else:
            if not NormalSong.check_song(form.name.data,current_user.type_session):
                form.premium.data = 2
            else:
                form.premium.data = None
                
        if form.content.data == '':#content
            form.content.data = None
        
        if form.cover.data == '':#cover
            form.cover.data = None
        else:
            album = Artist.check_link(form.cover.data)
        
        if form.album.data == list_albums_names[0]:#album
            form.album.data = None
        elif form.album.data == '':
            form.album.data = -1
        else:
            form.album.data = Album.extract_id_album(list_albums, form.album.data)
            album = Album.get_albums_id(form.album.data)
            form.cover.data = album.cover
            album = True
        if album == False: #checking cover,content and if ok calling update
            flash("Error Cover Link.")
        elif (not Artist.check_link(form.content.data)) and (form.content.data != None) :
            flash("Error Content Link.")
        else:
            if album != True and form.cover.data != None:
                form.cover.data =form.cover.data.split("/")[5]
            if Artist.modify_song(song_info.idsong,form.name.data,form.album.data,form.cover.data,
                                form.content.data,form.release_date.data,form.genre.data,form.premium.data, current_user.type_session):
                flash("Modification Successful")
                return redirect(url_for('artist.song'))
            else:
                flash("Error loading modification.")
    return render_template('modifysong.html', form = form, user = current_user, song = song_info)

@artist.route('/deletesong', methods=['POST'])
@login_required
def deletesong():
    if current_user.type_account != 3:
        abort(403)
        
    delete_song = DeleteSong()
    if delete_song.validate_on_submit():
        if Artist.delete_song(delete_song.idsong.data, current_user.type_session):
            flash("Delete successful.")
        else:
            flash("Error song delete.")
    return redirect(url_for('artist.song'))

Progetto_PineappleMusic/Codice/artist/templates/album.html
{% extends 'menu.html' %}

{% block content %}

<div class="d-flex justify-content-center dashboard-content px-3 pt-4  text-center">
    <div class="container">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <h1>Album {{user.username}}</h1>
                <br>
                <h4>Create New Album</h4>
                <form method="POST" action="">
                    {{ form.csrf_token }}
                    <hr class="h-color-black mx-2">   
    
                    <div class="3row gx- mb-3">
                            <!-- Form Group (organization name)-->
    
                        {{ form.name.label(class="form-label")}} 
                        {{ form.name(class="form-control")}}
    
                            <!-- Form Group (location)-->
                    </div>
    
                    <div class="3row gx-3 mb-3">
                        <!-- Form Group (organization name)-->
    
                        {{ form.cover.label(class="form-label")}} 
                        {{ form.cover(class="form-control")}}
    
                        <!-- Form Group (location)-->
                    </div>
                    
    
                    
                    <!-- Save changes button-->
                    {{ form.submit(class="btn btn-success")}}
                </form>
    
                
            </div>
            <div class="col-3"></div>

            <br>
            <h4>Manage Album</h4>
            <div class="col-12 table-responsive">
                <table id="playlisttable" class="table table-striped" style="width:100%">
                    <thead class="table-dark">
                        <tr>
                            <th>Cover</th>
                            <th>Name</th>
                            <th>Modify Album</th>
                            <th>Delete Album</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in album %}
                        <tr class="table-light">
                            <td><img src="https://drive.google.com/uc?export=view&id={{item.cover}}" height="50" width="50"></td>
                            <td>{{item.name}}</td>
                            <form method="POST" action="{{ url_for('artist.modifyalbum') }}">
                                {{ modify_album.csrf_token }}
                                {{modify_album.idalbum(value=item.idalbum)}}
                                <td>{{modify_album.submit(class="btn btn-primary",value="Modify")}}</td>
                            </form>
                            <form method="POST" action="{{ url_for('artist.deletealbum') }}">
                                {{ delete_album.csrf_token }}
                                {{delete_album.idalbum(value=item.idalbum)}}
                                <td>{{delete_album.submit(class="btn btn-danger",value="Delete")}}</td>
                            </form>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
            <div class="col-6 container">
            {% for message in get_flashed_messages()%}
                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                      {{message}}
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
            {%endfor%}
            </div>
        </div>

    </div>
</div>

{% endblock %}

Progetto_PineappleMusic/Codice/artist/templates/modifyalbum.html
{% extends 'menu.html' %}

{% block content %}


<div class="d-flex justify-content-center dashboard-content px-3 pt-4  text-center">
    <!-- Account details card-->

    <div class="">Modify Album  {{user.username}}
        <div class="">
            
            <!-- Form Group (username)-->
            <form method="POST" action="">
                {{ form.csrf_token }}
                <hr class="h-color-black mx-2">   

                <div class="row gx-3 mb-3">
                        <!-- Form Group (organization name)-->
                    {{ form.idalbum(class="form-control",value=album.idalbum)}}

                    {{ form.name.label(class="form-label")}} 
                    {{ form.name(class="form-control",value=album.name)}}

                        <!-- Form Group (location)-->
                </div>

                <div class="row gx-3 mb-3">
                    <!-- Form Group (organization name)-->

                    {{ form.cover.label(class="form-label")}} 
                    {{ form.cover(class="form-control")}}

                    <!-- Form Group (location)-->
                </div>
                
                
                <!-- Save changes button-->
                {{ form.submit(class="btn btn-success")}}
            </form>

            

            {% for message in get_flashed_messages()%}
                <div class="alert alert-primary alert-dismissible fade show" role="alert">
                  {{message}}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {%endfor%}
        </div>
    </div>
</div>

{% endblock %}

Progetto_PineappleMusic/Codice/artist/templates/modifysong.html
{% extends 'menu.html' %}

{% block content %}


<div class="d-flex justify-content-center dashboard-content px-3 pt-4  text-center">
<div class="container">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <h1>Song {{user.username}}</h1>
                <br>
                <h4>Create New Song</h4>
                
                <form method="POST" action="">
                    {{ form.csrf_token }}
                    <hr class="h-color-black mx-2">   
    
                    <div class="row gx-3 mb-3">
                            <!-- Form Group (organization name)-->
                        {{ form.idsong(value=song.idsong)}}

    
                        {{ form.name.label(class="form-label")}} 
                        {{ form.name(class="form-control", value=song.name)}}
    
                            <!-- Form Group (location)-->
                    </div>
                    
                    <div>
                        <img src="https://drive.google.com/uc?export=view&id={{song.cover}}" height="200" width="200" style="border-radius: 15px;" >
                    </div>


                    <div class="row gx-3 mb-3">
                        <!-- Form Group (organization name)-->
    
                        {{ form.cover.label(class="form-label")}} 
                        {{ form.cover(class="form-control")}}
    
                        <!-- Form Group (location)-->
                    </div>

                    <div class="row gx-3 mb-3">
                        <audio style="border-radius: 25px;" controls  >
                            <source src="https://drive.google.com/uc?export=view&id={{song.content}}" type="audio/mpeg"  > 
                            Your browser does not support the audio element.
                        </audio>
                    </div>
                    
                    <div class="row gx-3 mb-3">
                        <!-- Form Group (organization name)-->
    
                        {{ form.content.label(class="form-label")}} 
                        {{ form.content(class="form-control")}}
    
                        <!-- Form Group (location)-->
                    </div>
    
                    <div class="row gx-3 mb-3">
                            <!-- Form Group (first name)-->
                        <div class="col-md-6">
                            {{ form.genre.label(class="small mb-1")}} 
                            {{ form.genre(class="form-control")}}
    
                        </div>
                            <!-- Form Group (last name)-->
                        <div class="col-md-6">
                                {{ form.album.label(class="small mb-1")}} 
                                {{ form.album(class="form-control")}}
                        </div>
                    </div>
                        <!-- Form Row        -->
    
    
                        <!-- Form Row-->
                    <div class="row gx-3 mb-3">
                            <!-- Form Group (phone number)-->
                        <div class="col-md-6">
                            {{ form.release_date.label(class="small mb-1")}} 
                            {{ form.release_date(class="form-control", value=song.releasedate)}}
                        </div>
                            <!-- Form Group (birthday)-->
                        <div class="col-md-6">
                            {{ form.premium.label(class="small mb-1")}} 
                            {{ form.premium(class="form-control")}}
                        </div>
                    </div>
            
                    <!-- Save changes button-->
                    {{ form.submit(class="btn btn-success")}}
                </form>
                
            </div>
            
            <div class="col-6 container">
            {% for message in get_flashed_messages()%}
                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                      {{message}}
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
            {%endfor%}
            </div>
        </div>

    </div>
</div>

{% endblock %}

Progetto_PineappleMusic/Codice/artist/templates/song.html
{% extends 'menu.html' %}

{% block content %}


<div class="d-flex justify-content-center dashboard-content px-3 pt-4  text-center">
<div class="container">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <h1>Song {{user.username}}</h1>
                <br>
                <h4>Create New Song</h4>
                
                <form method="POST" action="">
                    {{ form.csrf_token }}
                    <hr class="h-color-black mx-2">   
    
                    <div class="row gx-3 mb-3">
                            <!-- Form Group (organization name)-->
    
                        {{ form.name.label(class="form-label")}} 
                        {{ form.name(class="form-control")}}
    
                            <!-- Form Group (location)-->
                    </div>
    
                    <div class="row gx-3 mb-3">
                        <!-- Form Group (organization name)-->
    
                        {{ form.cover.label(class="form-label")}} 
                        {{ form.cover(class="form-control")}}
    
                        <!-- Form Group (location)-->
                    </div>
                    <div class="row gx-3 mb-3">
                        <!-- Form Group (organization name)-->
    
                        {{ form.content.label(class="form-label")}} 
                        {{ form.content(class="form-control")}}
    
                        <!-- Form Group (location)-->
                    </div>
    
                    <div class="row gx-3 mb-3">
                            <!-- Form Group (first name)-->
                        <div class="col-md-6">
                            {{ form.genre.label(class="small mb-1")}} 
                            {{ form.genre(class="form-control")}}
    
                        </div>
                            <!-- Form Group (last name)-->
                        <div class="col-md-6">
                                {{ form.album.label(class="small mb-1")}} 
                                {{ form.album(class="form-control")}}
                        </div>
                    </div>
                        <!-- Form Row        -->
    
    
                        <!-- Form Row-->
                    <div class="row gx-3 mb-3">
                            <!-- Form Group (phone number)-->
                        <div class="col-md-6">
                            {{ form.release_date.label(class="small mb-1")}} 
                            {{ form.release_date(class="form-control")}}
                        </div>
                            <!-- Form Group (birthday)-->
                        <div class="col-md-6">
                            {{ form.premium.label(class="small mb-1")}} 
                            {{ form.premium(class="form-control")}}
                        </div>
                    </div>
            
                    <!-- Save changes button-->
                    {{ form.submit(class="btn btn-success")}}
                </form>
                
            </div>
            <div class="col-3"></div>

            <br>
            <h4>Manage Song</h4>
            <div class="col-12 table-responsive">
                <table id="playlisttable" class="table table-striped" style="width:100%">
                    <thead class="table-dark">
                        <tr>
                            <th>Cover</th>
                            <th>Name</th>
                            <th>Modify Song</th>
                            <th>Delete Song</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in songs %}
                        <tr class="table-light">
                            <td><img src="https://drive.google.com/uc?export=view&id={{item.cover}}" height="50" width="50"></td>
                            <td>{{item.name}}</td>
                            <form method="POST" action="{{ url_for('artist.modifysong') }}">
                                {{ modify_song.csrf_token }}
                                {{modify_song.idsong(value=item.idsong)}}
                                <td>{{modify_song.submit(class="btn btn-primary",value="Modify")}}</td>
                            </form>
                            <form method="POST" action="{{ url_for('artist.deletesong') }}">
                                {{ delete_song.csrf_token }}
                                {{delete_song.idsong(value=item.idsong)}}
                                <td>{{delete_song.submit(class="btn btn-danger",value="Delete")}}</td>
                            </form>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
            <div class="col-6 container">
            {% for message in get_flashed_messages()%}
                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                      {{message}}
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
            {%endfor%}
            </div>
        </div>

    </div>
</div>

{% endblock %}

Progetto_PineappleMusic/Codice/artist/templates/statistics.html
{% extends 'menu.html' %}
{% block content %}

<div class="d-flex justify-content-center dashboard-content px-3 pt-4  text-center"></div>
  <div class="container-fluid">
  <div class="col-12">
    <h1 class="text-center">Statistics</h1>
  </div>
    
        <canvas id="views"></canvas>
        <br>
        <canvas id="upvote"></canvas>
        <br>
        <canvas id="downvote"></canvas>
    </div>
</div>


<script>
    //graph views
    const labels=[];
    const view=[];
    const upvote=[];
    const downvote=[];
    {% for item in views %}
    labels.push('{{item.name}}');
    view.push({{item.views}});
    upvote.push({{item.upvote}});
    downvote.push({{item.downvote}});
    {% endfor %}  
    new Chart(document.getElementById("views"), {
      type: 'bar',
      data: {
        labels: labels,
        datasets: [
          {
            label: "Views for every Song",
            backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
            data: view
          }
        ]
      },
      options: {
        legend: { display: false },
        responsive: true,
        plugins: {
          legend: {
            position: 'right',
          },
          title: {
            display: true,
            text: 'Views'
          }
        }
      }
  });
  //graph upvote
  new Chart(document.getElementById("upvote"), {
    type: 'bar',
    data: {
      labels: labels,
      datasets: [
        {
          label: "Like for every Song",
          backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
          data: upvote
        }
      ]
    },
      options: {
        indexAxis: 'y',
        elements: {
          bar: {
            borderWidth: 2,
          }
        },
        responsive: true,
        plugins: {
          legend: {
            position: 'right',
          },
          title: {
            display: true,
            text: 'Like'
          }
        }
      }
});

  //graph downvote
  new Chart(document.getElementById("downvote"), {
    type: 'bar',
    data: {
      labels: labels,
      datasets: [
        {
          label: "Dislike for every Song",
          backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
          data: downvote
        }
      ]
    },
      options: {
        indexAxis: 'y',
        elements: {
          bar: {
            borderWidth: 2,
          }
        },
        responsive: true,
        plugins: {
          legend: {
            position: 'right',
          },
          title: {
            display: true,
            text: 'Dislike'
          }
        }
      }
});
  </script>

{% endblock %}