Progetto_PineappleMusic/Codice/music/forms.py
from flask_wtf import FlaskForm
from wtforms import  StringField,SubmitField,SelectMultipleField,HiddenField
from wtforms.validators import DataRequired, Length


from Codice.models import *
from Codice.database import *
from Codice.artist.forms import *

class PlaylistForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired(),Length(1,20)])
    submit = SubmitField("Create")

class AddToPlaylist(FlaskForm):
    playlist = SelectMultipleField("Add to playlist")
    songid = HiddenField("Song Name")
    submit = SubmitField("Add")
    
class GetSongsPlaylist(FlaskForm):
    playlistid = HiddenField("id")
    name = HiddenField("name")
    submit = SubmitField("Add")

class DeleteSongFromPlaylist(FlaskForm):
    playlistid = HiddenField("id")
    idsong = HiddenField("name")
    submit = SubmitField("Delete")

class DeletePlaylist(FlaskForm):
    playlistid = HiddenField("id")
    submit = SubmitField("Delete")

class GetSongsGenres(FlaskForm):
    genre = HiddenField("genre")
    
    

Progetto_PineappleMusic/Codice/music/routes.py
from flask import Blueprint, render_template, flash,redirect,url_for, request, abort
from flask_login import  login_required,current_user

import json
from Codice.user.forms import TableChoice

from Codice.models import *
from Codice.database import *
from .forms import DeletePlaylist, DeleteSongFromPlaylist, PlaylistForm,AddToPlaylist,GetSongsPlaylist,GetSongsGenres


# Blueprint Configuration
music = Blueprint('music', __name__, static_folder='static',
                 template_folder='templates')


@music.route('/views', methods=['GET','POST'])
@login_required
def views():
    var=request.data
    data = json.loads(var)
    #print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAa", var)
    #if data["upvote"] == "up":
    #    print("AAAAAAAAAAAAAAAAAAAAAAAA")
    
    if data["view"] == "true":
        Statistic.increase_views(int(data["idsong"]),current_user.type_session)
        #print("AAAAAAAAAAAAAAAAAAAAAAAAAA")  
    elif "upvote" in data:
        if data["upvote"] == "up":
            like = True
            Record.delete(current_user.username, int(data["idsong"]),current_user.type_session)
            Record.insert(current_user.username, int(data["idsong"]), like,current_user.type_session)  
        elif data["downvote"] == "down":
            like = False
            Record.delete(current_user.username, int(data["idsong"]), current_user.type_session)
            Record.insert(current_user.username, int(data["idsong"]), like, current_user.type_session)  
        elif data["upvote"] == "null" and data["downvote"] == "null":
            Record.delete(current_user.username, int(data["idsong"]), current_user.type_session)
        
    return "ok"



@music.route('/search', methods=['GET','POST'])
@login_required
def search():
    form=AddToPlaylist()
    
    print(current_user.type_session,current_user.username)

    playlist = Playlist.get_playlist_user(current_user.type_session,current_user.username)
    form.playlist.choices=Playlist.get_playlist_name_id(current_user.type_session,playlist)

    song=Song.get_songs(current_user.username,current_user.type_session)

    
    
    
    if form.validate_on_submit():
        for idl in form.playlist.data:
            Contains.create(form.songid.data, idl, current_user.type_session)
    
    return render_template("songs.html",user=current_user,page_name="Search Songs",add_to_playlist=True,
                           listsong=song,playlist=playlist,form=form)


@music.route('/playlist', methods=['GET','POST'])
@login_required
def playlist():
    form=PlaylistForm()
    playlistform=GetSongsPlaylist()
    deleteplaylist=DeletePlaylist()
    session=current_user.type_session
    if form.validate_on_submit():
        if Playlist.create(session,form.name.data,current_user.username):
            flash("Succesful Creation")
        else:
            flash("Creation Failed")
    
    if deleteplaylist.validate_on_submit():
        Playlist.delete_playlist(deleteplaylist.playlistid.data, current_user.type_session)
            
    return render_template("playlist.html",user=current_user, form=form,
                           playlistform=playlistform,delete_playlist=deleteplaylist,
                           playlist=Playlist.get_playlist_user(session,current_user.username))


@music.route('/getsongfromplaylist', methods=['POST'])
@login_required
def getsongfromplaylist():
    form=GetSongsPlaylist()
    delete_form=DeleteSongFromPlaylist()
    if form.validate_on_submit():
        if delete_form.validate_on_submit():
            Contains.delete_song_from_playlist(delete_form.idsong.data,delete_form.playlistid.data, current_user.type_session)

        song=Song.get_song_playlist(current_user.username,form.playlistid.data)
        return render_template("songs.html",user=current_user,page_name="Playlist",
                listsong=song,delete_from_playlist=True,delete_form=delete_form,playlistid=form.playlistid.data)


@music.route('/getsongfromplaylist', methods=['GET'])
@login_required
def getsongfromplaylist_redirect():
    return redirect(url_for('music.playlist'))


@music.route('/getsongfromgenre', methods=['POST'])
@login_required
def getsongfromgenre():
    form=AddToPlaylist()
    genre_form=GetSongsGenres()
    session=User.get_type_user_session(current_user.username)

    if genre_form.validate_on_submit():
        song = Song.get_songs(current_user.username,current_user.type_session, genre_form.genre.data)

        playlist = Playlist.get_playlist_user(session,current_user.username)
        form.playlist.choices=Playlist.get_playlist_name_id(session,playlist)
        
        if form.validate_on_submit():
            for idl in form.playlist.data:
                Contains.create(form.songid.data, idl, current_user.type_session)
        
        return render_template("songs.html",user=current_user,page_name=genre_form.genre.data,add_to_playlist=True,
                            listsong=song,playlist=playlist,form=form)


@music.route('/getsongfromgenre', methods=['GET'])
@login_required
def getsongfromgenre_redirect():
    return redirect(url_for('user.home'))



@music.route('/getsongfromhome', methods=['GET'])
@login_required
def getsongfromhomeget_redirect():
    return redirect(url_for('user.home'))


@music.route('/getsongfromhome', methods=['POST'])
@login_required
def getsongfromhome():
    form_choice = TableChoice()
    form=AddToPlaylist()
    if form_choice.validate_on_submit():
        
        if form_choice.choice.data == 'views':
            song = Song.get_top_view_songs(current_user.type_session,True,current_user.username)
            pagename="TOP 10 VIEWS"
        elif form_choice.choice.data == 'likes':
            song = Song.get_top_like_songs(current_user.type_session,True,current_user.username)
            pagename="TOP 10 LIKES"
        elif form_choice.choice.data == 'suggestions':
            song = Song.get_suggestion_songs(current_user.username,current_user.type_session, True)
            pagename="YOUR SUGGESTION"
            if song == None:
                song = Song.get_top_view_songs(current_user.type_session,True,current_user.username)
        else:
            abort(412)
        playlist = Playlist.get_playlist_user(current_user.type_session,current_user.username)
        form.playlist.choices=Playlist.get_playlist_name_id(current_user.type_session,playlist)
        
    return render_template("songs.html",user=current_user,page_name=pagename,add_to_playlist=True,
                            listsong=song,playlist=playlist,form=form)

Progetto_PineappleMusic/Codice/music/templates/playlist.html
{% extends 'menu.html' %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('music.static',filename='css/style.css') }}">
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ url_for('music.static', filename='js/playlist.js')}}"></script>
{% endblock %}

{% block content %}

<div class="d-flex justify-content-center dashboard-content px-3 pt-4  text-center">
    <div class="container">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <h1>Create Your Playlists</h1>
                <div>
                    <form method="POST" action="{{ url_for('music.playlist') }}">
                        {{ form.csrf_token }}
                        <div class="row gx-3 mb-3 justify-content-center">
                            <div class="col-md-6 ">
                                {{ form.name.label(class="small mb-1")}}
                                {{ form.name(class="form-control")}}
                            </div>
                        </div>
                        {{ form.submit(class="btn btn-success")}}
                    </form>

                    {% for message in get_flashed_messages()%}
                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {%endfor%}

                </div>
            </div>
            <div class="col-3"></div>
            <div class="col-12 table-responsive">
                <table id="playlisttable" class="table table-striped" style="width:100%">
                    <thead class="table-dark">
                        <tr>
                            <th>Name</th>
                            <th>Creation Date</th>
                            <th>Play Playlist</th>
                            <th>Delete Playlist</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in playlist %}
                        <tr class="table-light">
                            <form method="POST" action="{{ url_for('music.getsongfromplaylist') }}">
                                {{ playlistform.csrf_token }}
                                <td>{{item.name}}{{playlistform.name(value=item.name)}}{{
                                    playlistform.playlistid(value=item.idlist)}}</td>
                                <td>{{item.creationdate}}</td>
                                <td>{{playlistform.submit(class="btn btn-primary",value="Listen")}}</td>
                            </form>
                            <form method="POST" action="{{ url_for('music.playlist') }}">
                                {{ delete_playlist.csrf_token }}
                                {{delete_playlist.playlistid(value=item.idlist)}}
                                <td>{{delete_playlist.submit(class="btn btn-danger",value="Delete")}}</td>
                            </form>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>

    </div>
</div>

{% endblock %}

Progetto_PineappleMusic/Codice/music/templates/songs.html
{% extends 'menu.html' %}
{% block css %}
    <link rel="stylesheet" href="{{ url_for('music.static',filename='css/style.css') }}">
{% endblock %}
{% block js %}
<script type="text/javascript" src="{{ url_for('music.static', filename='js/music.js')}}"></script>

<script>
    $(document).ready(function () {
        $('#example').DataTable({
            select: {
                style: 'single'
            }
        });

        var table = $('#example').DataTable();

        $('#example tbody').on('click', 'tr', function (e) {

            var text = e.target.nodeName;
            var view="false";

            if (text != "DIV" && text != "BUTTON" && text != "INPUT"&& text != "I") {
                var data = table.row(this).data();
                $("#coverplayer").attr("src", "https://drive.google.com/uc?export=view&id=" + $($(this).find("input")[0]).val());
                $("#title-song").text(data[2]);
                $("#artist-song").text(data[1]);
                $("#songnumber").val($($(this).find("input")[3]).val());
                $("#playerhidden").attr("src", "https://docs.google.com/uc?export=open&id=" + $($(this).find("input")[2]).val());
                $("#playerhidden").trigger("play");
                $('#playpause').attr('class', 'fa fa-light fa-pause');

                $("#playerhidden").on('loadedmetadata', function () {
                    var audioCurrentTime = document.getElementById("playerhidden").duration;
                    $("#time-dur").text(convert_to_time(audioCurrentTime));
                });

                view="true";

            }

            if(text=="I"){
                if ($(e.target).attr('class') == 'voteUp fa-regular fa-thumbs-up') {
                    $(e.target).attr('class', 'voteUp fa-solid fa-thumbs-up');
                    $(e.target).attr('vote','up');
                    e.target.parentElement.children[2].classList='voteDown fa-regular fa-thumbs-down';
                    e.target.parentElement.children[2].setAttribute('vote','null');
                } else if($(e.target).attr('class') == 'voteUp fa-solid fa-thumbs-up'){
                    $(e.target).attr('class', 'voteUp fa-regular fa-thumbs-up');
                    $(e.target).attr('vote','null');
                } else if($(e.target).attr('class') == 'voteDown fa-regular fa-thumbs-down') {
                    $(e.target).attr('class', 'voteDown fa-solid fa-thumbs-down');
                    $(e.target).attr('vote','down');
                    e.target.parentElement.children[0].classList='voteUp fa-regular fa-thumbs-up';
                    e.target.parentElement.children[0].setAttribute('vote','null');
                } else {
                    $(e.target).attr('class', 'voteDown fa-regular fa-thumbs-down');
                    $(e.target).attr('vote','null');
                }
            }

                var csrf_token = "{{ csrf_token() }}";

                $.ajax({
                    type: "POST",
                    headers: {
                        "X-CSRFToken": csrf_token,
                        "Content-Type": "application/json"
                    },
                    url: "/music/views",
                    data: JSON.stringify({ "idsong": $($(this).find("input")[1]).val(),"upvote":  $($(this).find(".voteUp")).attr("vote"),"downvote":  $($(this).find(".voteDown")).attr("vote"),"view":view}),
                    success: function (response) {
                        console.log(response);
                    },
                    error: function (response, error) {
                        console.log(response);
                        console.log(error);
                    }
                });

        });

        

        $("#progress-bar-song").on("click", function (e) {
            var pos_curr = e.pageX - $("#progress-bar-song").offset().left; //Position cursor
            var size_bar = document.getElementById("progress-bar-song").offsetWidth;
            $('#time-bar').attr('style', "width:" + pos_curr * 100 / size_bar + "%;");
            var duration = document.getElementById("playerhidden").duration;
            document.getElementById("playerhidden").currentTime = duration / 100 * pos_curr * 100 / size_bar;
        });


        $("#progress-bar-vol").on("click", function (e) {
            var pos_curr = e.pageX - $("#progress-bar-vol").offset().left; //Position cursor
            var size_bar = document.getElementById("progress-bar-vol").offsetWidth;
            var vol = pos_curr * 100 / size_bar;
            $('#progress-bar-vol-contr').attr('style', "width:" + parseFloat(vol.toFixed(1)) + "%;");
            document.getElementById("playerhidden").volume = pos_curr / size_bar;
            $('#icon-volume').attr('class', 'fas fa-volume-down');
        });

    });
</script>

{% endblock %}

{% block content %}
<div class="container-fluid song-list">

    <div class="col-12">
        <h1 class="text-center">{{page_name}}</h1>
    </div>

    <audio id="playerhidden" controls autoplay hidden>
        <source type="audio/mpeg">
    </audio>
    <input type="hidden" id="songnumber">

    <div class="col-12 table-responsive">
        <table id="example" class="table table-striped" style="width:100%">
            <thead class="table-dark">
                <tr>
                    <th>Cover</th>
                    <th>Artist</th>
                    <th>Name</th>
                    <th>Album</th>
                    <th>Genre</th>
                    <th>Vote</th>
                    {% if add_to_playlist%}
                    <th>Add to Playlist</th>
                    {% endif %}
                    {% if delete_from_playlist%}
                    <th>Delete from playlist</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% set i = namespace(value=0) %}
                {% for item in listsong %}
                <tr class="table-light">
                    <td><img src="https://drive.google.com/uc?export=view&id={{item[0].cover}}" height="50" width="50">
                        <input type="hidden" value="{{item[0].cover}}">
                        <input type="hidden" value="{{item[0].idsong}}">
                        <input type="hidden" value="{{item[0].content}}">
                        <input type="hidden" id='listsong' value="{{i.value}}">
                        {% set i.value = i.value + 1 %}
                    </td>
                    <input type="hidden" value="{{item[0].cover}}">
                    <input type="hidden" value="{{item[0].idsong}}">
                    <td>{{item.username}}</td>
                    <td>{{item[0].name}}</td>
                    <td>{{item.name}}</td>
                    <td>{{item.genre}}</td>
                    {% if item[6]==True %}
                        <td><i class="voteUp fa-solid fa-thumbs-up" vote="up"></i> <p>    </p> <i class="voteDown fa-regular fa-thumbs-down" vote="null" ></i></td>
                    {% elif item[6]==False %}
                        <td><i class="voteUp fa-regular fa-thumbs-up" vote="null"></i> <p>    </p>    <i class="voteDown fa-solid fa-thumbs-down" vote="down"></i></td>
                    {% else %}
                        <td><i class="voteUp fa-regular fa-thumbs-up" vote="null"></i> <p>    </p> <i class="voteDown fa-regular fa-thumbs-down" vote="null"></i></td>
                    {% endif %}
                    {% if add_to_playlist%}
                    <td>
                        <form method="POST" action="{{ url_for('music.search') }}">
                            {{ form.csrf_token }}
                            {{ form.songid(value=item[0].idsong)}}
                            {{
                            form.playlist(class="selectpicker",multiple=True,**{"data-live-search":"true","title":"List
                            of your playlist"})}}
                            {{ form.submit(class="btn btn-success")}}
                        </form>
                    </td>
                    {% endif %}
                    
                    {% if delete_from_playlist%}
                    <form method="POST" action="{{ url_for('music.getsongfromplaylist') }}">
                        {{ delete_form.csrf_token }}
                        {{ delete_form.idsong(value=item[0].idsong)}}
                        {{ delete_form.playlistid(value=playlistid)}}
                        <td>{{ delete_form.submit(class="btn btn-danger")}}</td>
                    </form>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
</div>
<input type="hidden" id="maxsongnumber" value="{{i.value}}">


<div class="music-player col-10">
    <div class="song-bar" n>
        <div class="song-infos">
            <div class="image-container">
                <img id="coverplayer" src="{{ url_for('static', filename='img/pineapplemusic.ico')}}" style='height: 100%; width: 100%; object-fit: contain' alt="cover" />
            </div>
            <div class="song-description">
                <p class="title" id="title-song">

                </p>
                <p class="artist" id="artist-song">Artist Name</p>
            </div>
        </div>

    </div>
    <div class="progress-controller">
        <div class="control-buttons">
            <i class="fas fa-step-backward" id="backsong"></i>
            <i class="play-pause fas fa-play" id="playpause"></i>
            <i class="fas fa-step-forward" id="nextsong"></i>
            <i class="fas fa-undo-alt" id="repeatsong"></i>
        </div>
        <div class="progress-container">
            <span id="time-att">0:00</span>
            <div class="progress-bar" id="progress-bar-song">
                <div class="progress " id="time-bar" style="width: 0%;"></div>
            </div>
            <span id="time-dur">3:15</span>
        </div>
    </div>

    <div class="other-features">

        <div class="volume-bar">
            <i class="fas fa-volume-down" id="icon-volume"></i>
            <div class="progress-bar" id="progress-bar-vol">
                <div class="progress" id="progress-bar-vol-contr" style="width: 100%;"></div>
            </div>
        </div>
    </div>
</div>


{% endblock %}