Progetto_PineappleMusic/Codice/user/forms.py
from flask_wtf import FlaskForm
from wtforms import  StringField, PasswordField,DateField,SubmitField,EmailField, SelectField, HiddenField
from wtforms.validators import DataRequired, Length, Email, Optional

months = ['',1,2,3,4,5,6,7,8,9,10,11,12]
years = ['', 2022, 2023, 2024, 2025, 2026, 2027]

class ModifyProfileForm(FlaskForm):
    
    
    name = StringField("Name", validators=[DataRequired(),Length(max=20)])
    surname = StringField("Surname", validators=[DataRequired(),Length(max=20)])
    birthdate = DateField("Birthdate", validators=[DataRequired()])
    password = PasswordField("Password", validators=[Optional(), Length(min=8)])
    
    phone = StringField("Phone", validators=[DataRequired(),Length(min=10,max=13)])
    email = EmailField("Email", validators=[DataRequired(),Email()])
    
    submit = SubmitField("Update")
    
    
class CrediCardForm(FlaskForm):
    
    card_number = StringField("CardNumber", validators=[DataRequired(), Length(min=16,max=16)])
    month = SelectField("Month", choices=months, validate_choice=True )
    year = SelectField("Year", choices=years, validate_choice=True )
    cvv =StringField("CVV", validators=[DataRequired(), Length(min=3,max=3)])
  
    submit = SubmitField("Update")
    
class TableChoice(FlaskForm):
    choice = HiddenField("choice")

Progetto_PineappleMusic/Codice/user/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, logout_user, current_user

from Codice.database import *
from Codice.user.forms import CrediCardForm, ModifyProfileForm, TableChoice
from Codice.music.forms import GetSongsGenres
from Codice.models import *

# Blueprint Configuration
user = Blueprint('user', __name__, static_folder='static',
                 template_folder='templates')


@user.route('/home', methods=['GET'])
@login_required
def home():
    likes = Song.get_top_like_songs(current_user.type_session)
    views = Song.get_top_view_songs(current_user.type_session)
    suggestion = Song.get_suggestion_songs(current_user.username, current_user.type_session)
    print("SUGGESTION: ", suggestion)
    if suggestion == None:
        suggestion = views
    form_redirect = TableChoice()    
    form_genre=GetSongsGenres()
    genres=Genre.get_genres()
    
    return render_template("home.html", title="Home", form_genre=form_genre,user=current_user,genres=genres, songview = views, songlike = likes, songsuggestion = suggestion, form_redirect = form_redirect)


@user.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = ModifyProfileForm()
    if form.validate_on_submit():
        if form.password.data == '':
            check_password = False
        else:
            check_password = True
            form.password.data = User.encrypt_password(form.password.data)
        if User.update_user(current_user.type_session,
                            current_user.username, form.name.data,
                            form.surname.data, form.birthdate.data,
                            form.password.data, form.phone.data, form.email.data,
                            check_password):
            flash('Update Successful')
            return redirect(url_for('user.profile'))
        else:
            flash('Update Failed')
    return render_template("profile.html", title="Profile", user=current_user, form=form)


@user.route('/delete', methods=['POST'])
@login_required
def delete():
    User.delete_user(current_user.username)
    logout_user()
    flash('Your account was deleted.')
    return redirect(url_for('auth.signin'))


@user.route('/premium', methods=['GET', 'POST'])
@login_required
def premium():
    form = CrediCardForm()
    if form.validate_on_submit():
        if not form.card_number.data.isnumeric():
            flash("Card Number not valid.(Don't use letters!)")
        elif not form.cvv.data.isnumeric():
            flash("CVV not valid(Don't use letters!)")
        else:
            if User.move_user_to_premium(current_user.username):
                flash("Ugrade Succesful. YOU ROCK!")
            else:
                flash("Upgrade Failed.")
    return render_template("premium.html", title="Premium Account", user=current_user, form=form)

Progetto_PineappleMusic/Codice/user/templates/home.html
{% extends 'menu.html' %}
{% block js %}
  <script type="text/javascript" src="{{ url_for('user.static', filename='js/script.js')}}"></script>
{% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    <h1 class="text-center">Home</h1>
    {% for item in genres %}
      <div class="col-lg-3 col-6">
        <div class="card card-music text-white bg-success mb-3" type="submit" style="max-width: 18rem;">
          <form method="POST" action="{{ url_for('music.getsongfromgenre') }}">
            {{ form_genre.csrf_token }}
            {{ form_genre.genre(value=item.name)}}
            <div class="img card-img-top"
              style="background-image: url(https://drive.google.com/uc?export=view&id={{item.cover}})"></div>
            <div class="card-body">
              <h5 class="card-title" style="text-align: center">{{item.name}}</h5>
            </div>
          </form>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

<br>
<br>

<h2 style="text-align: center">TOP 10 VIEWS</h2>
<div class="container-fluid song-list">

  <div class="col-12 table-responsive">
    <form id="formtest1" method="POST" action="{{ url_for('music.getsongfromhome') }}">
      {{ form_redirect.csrf_token }}
    <table id="test1" class="table table-striped" style="width:100%">
      <thead class="table-dark">
        <tr>
          <th>Cover</th>
          <th>Name</th>
          <th>Artist</th>
          <th>Genre</th>
          <th>Album</th>
          <th>Views</th>
        </tr>
      </thead>
      <tbody>
        {% for item in songview %}
          <tr class="table-light">
            <td><img src="https://drive.google.com/uc?export=view&id={{item.cover}}" height="50" width="50"></td>
            <td>{{item.name}}</td>
            <td>{{item.artist}}</td>
            <td>{{item.genre}}</td>
            <td>{{item.album}}</td>
            <td>{{item.views}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {{ form_redirect.choice(class="form-control",value="views")}}
  </form>
  </div>
</div>

<h2 style="text-align: center">TOP 10 LIKES</h2>
<div class="container-fluid song-list">

  <div class="col-12 table-responsive">
    <form id="formtest2" method="POST" action="{{ url_for('music.getsongfromhome') }}">
      {{ form_redirect.csrf_token }}
    <table id="test2" class="table table-striped" style="width:100%">
      <thead class="table-dark">
        <tr>
          <th>Cover</th>
          <th>Name</th>
          <th>Artist</th>
          <th>Genre</th>
          <th>Album</th>
          <th>Likes</th>
        </tr>
      </thead>
      <tbody>
        {% for item in songlike %}
          <tr class="table-light">
            <td><img src="https://drive.google.com/uc?export=view&id={{item.cover}}" height="50" width="50"></td>
            <td>{{item.name}}</td>
            <td>{{item.artist}}</td>
            <td>{{item.genre}}</td>
            <td>{{item.album}}</td>
            <td>{{item.likes}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {{ form_redirect.choice(class="form-control",value="likes")}}
  </form>
  </div>
</div>

<h2 style="text-align: center">YOUR SUGGESTION</h2>
<div class="container-fluid song-list">
  <div class="col-12 table-responsive">
    <form id="formtest3" method="POST" action="{{ url_for('music.getsongfromhome') }}">
      {{ form_redirect.csrf_token }}
    <table id="test3" class="table table-striped" style="width:100%">
      <thead class="table-dark">
        <tr>
          <th>Cover</th>
          <th>Name</th>
          <th>Artist</th>
          <th>Genre</th>
          <th>Album</th>
        </tr>
      </thead>
      <tbody>
        {% for item in songsuggestion %}
          <tr class="table-light">
            <td><img src="https://drive.google.com/uc?export=view&id={{item.cover}}" height="50" width="50"></td>
            <td>{{item.name}}</td>
            <td>{{item.artist}}</td>
            <td>{{item.genre}}</td>
            <td>{{item.album}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {{ form_redirect.choice(class="form-control",value="suggestions")}}
  </form>
  </div>
</div>




{% endblock %}

Progetto_PineappleMusic/Codice/user/templates/premium.html
{% extends 'menu.html' %}

{% block content %}


<div class="d-flex justify-content-center dashboard-content px-3 pt-4  text-center">

    <div class="">Update your account to Premium
        <div class="">
            <form method="POST" action="{{ url_for('user.premium') }}">
                {{ form.csrf_token }}
                <hr class="h-color-black mx-2">
                <div class="col-md-12">
                    <label class="small mb-1">Username</label>
                    <input class="form-control text-center" type="text" value="{{user.username}}" readonly>
                </div>
                <div class="row gx-3 mb-3">
                    {{ form.card_number.label(class="form-label")}}
                    {{ form.card_number(class="form-control",placeholder="xxxx xxxx xxxx xxxx")}}
                </div>
                <div class="row gx-3 mb-3">
                    <div class="col-md-6">
                        {{ form.month.label(class="small mb-1")}}
                        {{ form.month(class="form-control")}}

                    </div>
                    <div class="col-md-6">
                        {{ form.year.label(class="small mb-1")}}
                        {{ form.year(class="form-control")}}
                    </div>
                </div>
                <div class="row gx-3 mb-3">
                    <div class="col-md-6">
                        {{ form.cvv.label(class="form-label")}}
                        {{ form.cvv(class="form-control",placeholder="xxx")}}
                    </div>
                </div>
                {{ form.submit(class="btn btn-primary")}}
            </form>
            {% for message in get_flashed_messages()%}
            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {%endfor%}
        </div>
    </div>
</div>

{% endblock %}

Progetto_PineappleMusic/Codice/user/templates/profile.html
{% extends 'menu.html' %}

{% block content %}


<div class="d-flex justify-content-center dashboard-content px-3 pt-4  text-center">

    <div>
        <h1>Profile Info</h1>
        <div>
            <form method="POST" action="{{ url_for('user.profile') }}">
                {{ form.csrf_token }}
                <hr class="h-color-black mx-2">
                <div class="col-md-12">
                    <label class="small mb-1">Username</label>
                    <input class="form-control text-center" type="text" value="{{user.username}}" readonly>
                </div>

                <div class="row gx-3 mb-3">
                    <div class="col-md-6">
                        {{ form.name.label(class="small mb-1")}}
                        {{ form.name(class="form-control",value=user.name)}}

                    </div>
                    <div class="col-md-6">
                        {{ form.surname.label(class="small mb-1")}}
                        {{ form.surname(class="form-control",value=user.surname)}}
                    </div>
                </div>
                <div class="row gx-3 mb-3">
                    {{ form.birthdate.label(class="form-label")}}
                    {{ form.birthdate(class="form-control",value=user.birthdate)}}
                </div>
                <div class="mb-3">
                    <label class="small mb-1" for="inputGender">Gender</label>
                    <input class="form-control text-center" type="text" value="{{user.gender}}" readonly>
                </div>
                <div class="row gx-3 mb-3">
                    <div class="col-md-6">
                        {{ form.phone.label(class="small mb-1")}}
                        {{ form.phone(class="form-control",value=user.phone)}}
                    </div>
                    <div class="col-md-6">
                        {{ form.email.label(class="small mb-1")}}
                        {{ form.email(class="form-control",value=user.email)}}
                    </div>
                </div>
                <div class="mb-3">
                    {{ form.password.label(class="small mb-1")}}
                    <div class="form-group">
                        <div class="input-group" id="show_hide_password">
                            {{ form.password(class="form-control",value=user.password)}}
                            <div class="input-group-addon px-2 pt-2">
                                <a href=""><i class="fa-solid fa-eye" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                {{ form.submit(class="btn btn-success")}}
            </form>

            <form method="POST" action="{{ url_for('user.delete') }}">
                {{ form.csrf_token }}
                <button type="submit" class="btn btn-danger">Delete Account</button>
            </form>

            {% for message in get_flashed_messages()%}
            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {%endfor%}
        </div>
    </div>
</div>

{% endblock %}